### ISSUE TITLE
Messages are cut off after a colon (“:”)

### ISSUE THREAD

**Issue by benstm** [dtkdt100/receive_whatsapp_chat#1]
I noticed that messages are cut off after the first colon (“:”). This includes the colon unless it is at the very end.

For example, if I text this:
![image](https://user-images.githubusercontent.com/42867554/161373357-31015d61-34da-447e-93ad-906de39f6329.png)

_receive_whatsapp_chat_ gives me this:
![image](https://user-images.githubusercontent.com/42867554/161373380-4e2b68b5-4a27-4373-9939-bca20ac79672.png)

**Comment by dtkdt100** [comment]
Thanks for the report, I fixed it. 
See: https://github.com/dtkdt100/receive_whatsapp_chat/commit/fb62fb4dff99b2005ac4c1146c1112654a544e3d

**Comment by benstm** [comment]
Thank you for the quick fix!
