### ISSUE TITLE
*** URGENT *** Not working after update WhatsApp.

### ISSUE THREAD

**Issue by ashokavarthanan** [dtkdt100/receive_whatsapp_chat#10]
Hi, 
Recently I updated WhatsApp.
When using "Export Chat" the export is a "zip" file format.
so this plugin not working.

*** Note: Previously ( before update WhatsApp ) export is a "txt" file format.***
version: 0.1.4

Any idea?

Thanks.

update:
FlutterShareReceiverActivity.java

`if ("text/plain".equals(type))`

in this section only allowed text files.
can possible, when receive file type is zip, extract and use the text file?

**Comment by dtkdt100** [comment]
Hi!
Thanks for the issue report!
There is a new version that supports the new way for exporting chats in Android: 
```
receive_whatsapp_chat: ^0.1.5
```
