### ISSUE TITLE
Channel Error

### ISSUE THREAD

**Issue by Baxter92** [dtkdt100/receive_whatsapp_chat#2]
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method openwhatsapp on channel com.whatsapp.chat/openwhatsapp)

**Comment by dtkdt100** [comment]
Hi [Baxter92](https://github.com/Baxter92),

The channel `com.whatsapp.chat/openwhatsapp` is from the [example](https://github.com/dtkdt100/receive_whatsapp_chat/tree/main/example) in [receive_whatsapp_chat](https://github.com/dtkdt100/receive_whatsapp_chat) plugin, it is not part of the plugin.

First of all, to add the feature to open whatsapp (calling the channel above), you will need to copy the code in [example/android/app/main/java/.../MainActivity.java](https://github.com/dtkdt100/receive_whatsapp_chat/blob/main/example/android/app/src/main/java/com/whatsapp/receive_whatsapp_chat_example/MainActivity.java) into your MainActivity.java.

Secondly, you will do add `queries` for the package `com.whatsapp` in your `android/app/src/main/AndroidManifest.xml`. See [example](https://github.com/dtkdt100/receive_whatsapp_chat/blob/main/example/android/app/src/main/AndroidManifest.xml).

Best,
Dolev.
