### ISSUE TITLE
The method 'enableReceivingChatWithMedia' isn't defined for the type 'DemoAppState'.

### ISSUE THREAD

**Issue by varunlohade** [dtkdt100/receive_whatsapp_chat#6]
I have updated the plugin to the newest version but I am facing this issue.
![image](https://user-images.githubusercontent.com/50517140/174433752-47f5c0ea-8a5d-4dd6-bfd2-4ee004e3ad78.png)

![image](https://user-images.githubusercontent.com/50517140/174433711-63e0ba00-2387-4cb9-8f12-4747cc8a7696.png)

isImage() and getImage() are undefined.
Can you explain to me what the issue is?

**Comment by dtkdt100** [comment]
Hi, thank for the report.

Can you try run `flutter clean` and then `flutter pub get`?

Make sure your are on version `receive_whatsapp_chat: 0.1.3` and up.

**Comment by varunlohade** [comment]
Hey, Thanks the issue has been solved.
flutter clean did the work.

I wanted to ask one thing.
How do I store the chat data locally on an Android phone and then retrieve it?

**Comment by dtkdt100** [comment]
Hi, you can the package [shared_preferences](https://pub.dev/packages/shared_preferences) in order to store chat data on your Android and iOS phone.

For storing `ChatContent` in your deivce, use `toJson` function, and then parse it into a string using `json.encode()`.
For getting the stored `ChatContent`, just do the opposite: `json.decode()` and `fromJson`. 

### An example:

```dart 
class SharedPreferencesUtilities {
  static const String _chatKey = "chat";

  static late SharedPreferences prefs;

  static Future<void> init() async =>
      prefs = await SharedPreferences.getInstance();

  static void getAll() {
    getChat();
  }

  static Future<void> setChat(ChatContent chat) async {
    await prefs.setString(_chatKey, json.encode(chat.toJson()));
  }

  static ChatContent? getChat() {
    String? chat = prefs.getString(_chatKey);
    if (chats != null) return ChatContent.fromJson(json.decode(chat));
    return null;
  }
}
```
