### ISSUE TITLE
[Flutter 3.10.5] MissingPluginException(No implementation found for method listen on channel plugins.flutter.io/receiveshare)

### ISSUE THREAD

**Issue by XeroDays** [dtkdt100/receive_whatsapp_chat#8]
It has stopped working with the latest version, can you please look into it? because lots of people use your app.

<img width="1148" alt="image" src="https://github.com/dtkdt100/receive_whatsapp_chat/assets/38852291/2c76b5cc-e95a-45ea-b6fd-44d914bd374c">

**Comment by dtkdt100** [comment]
Hi, thanks for reporting!

I am going now on a trip for a week, so I will get into it then.

Make sure you did all the set-up in the README, and you re-run and pub-get the app after you add the plugin

**Comment by XeroDays** [comment]
Sure, Enjoy, Looking forward.
I've done everything, and downloaded your "example" as well but doesn't work on versions `3.10.5` and `3.7.12` .
No Results.
If you can update the example to the latest version, that will help.

**Comment by dtkdt100** [comment]
@XeroDays Hi!
I updated dark and flutter stks, gradle, kotlin.
I Checked it on version 3.13.1 and it works good.
![image](https://github.com/dtkdt100/receive_whatsapp_chat/assets/63166757/61df7561-f1e6-4291-a400-a37af528f8dc)

![image](https://github.com/dtkdt100/receive_whatsapp_chat/assets/63166757/5ad23f55-f2fb-4855-ab7e-05f947e660a8)

Make sure to follow this in REAME if you are using the example: https://github.com/dtkdt100/receive_whatsapp_chat/commit/25247dd02375f8778f0518979cc7ab2bb2156365

**Comment by XeroDays** [comment]
Great Work by the way! Keep it up.
